name: gauche
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip=21.1.3
  - jupyterlab=1.0.0
  - botorch
  - selfies
  - scikit-learn
  - pandas
  - pytest
  - tqdm
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - rxnfp
    - graphein==1.5.1
    - rdkit
    - torch-geometric == 1.7.2
