"""
A script containing utilities for the different data loader classes.
"""

import sys
from prody import *
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.Descriptors import qed
from io import StringIO
import requests
import os

# functions adapted from Pat Walters (https://gist.github.com/PatWalters/3c0a483c030a2c75cb22c4234f206973)
# that split a PDB entry into a .pdb file of the protein and a .sdf file of the ligand(s)


def read_ligand_expo():
    """
    Read PDB Ligand Expo data, try to find a file called
    Components-smiles-stereo-oe.smi in the current directory.
    If you can't find the file, grab it from the RCSB

    Returns: Ligand Expo as a dictionary with ligand id as the key

    """

    file_name = "Components-smiles-stereo-oe.smi"

    # read file if it already exists
    try:
        df = pd.read_csv(file_name, sep="\t",
                         header=None,
                         names=["SMILES", "ID", "Name"])

    # otherwise download it and read it in afterwards
    except FileNotFoundError:
        url = f"http://ligand-expo.rcsb.org/dictionaries/{file_name}"
        r = requests.get(url, allow_redirects=True)
        open('Components-smiles-stereo-oe.smi', 'wb').write(r.content)
        df = pd.read_csv(file_name, sep="\t",
                         header=None,
                         names=["SMILES", "ID", "Name"])
    df.set_index("ID", inplace=True)

    return df.to_dict()


def get_pdb_components(pdb_id):
    """
    Split a protein-ligand pdb into protein and ligand components.
    A useful dictionary of possible flags can be found here
    http://prody.csb.pitt.edu/manual/reference/atomic/flags.html#flags.

    Args:
        pdb_id: 4-letter pdb code

    Returns: tuple of ProDy Selections for proteins and ligands

    """

    pdb = parsePDB(pdb_id)
    protein = pdb.select('protein')
    ligand = pdb.select('not protein and not water and not ion')
    return protein, ligand


def process_ligand(ligand, res_name, expo_dict):
    """
    Add bond orders to a pdb ligand through the following process
    1. Select the ligand component with name "res_name"
    2. Get the corresponding SMILES from the Ligand Expo dictionary
    3. Create a template molecule from the SMILES in step 2
    4. Write the PDB file to a stream
    5. Read the stream into an RDKit molecule
    6. Assign the bond orders from the template from step 3

    Args:
        ligand: ligand as generated by prody
        res_name: residue name of ligand to extract
        expo_dict: dictionary with LigandExpo

    Returns: molecule with bond orders assigned

    """

    output = StringIO()

    # select res_name residue
    sub_mol = ligand.select(f"resname {res_name}")

    # extract corresponding SMILES and read it into rdkit
    sub_smiles = expo_dict['SMILES'][res_name]
    template = AllChem.MolFromSmiles(sub_smiles)

    # calculate the rdkit drug likeness descripot for the ligand expo template
    drug_likeness = qed(template)

    # stream selected ligand
    writePDBStream(output, sub_mol)
    pdb_string = output.getvalue()

    # add bond orders
    rd_mol = AllChem.MolFromPDBBlock(pdb_string)
    new_mol = AllChem.AssignBondOrdersFromTemplate(template, rd_mol)

    return new_mol, drug_likeness


def write_pdb(protein, pdb_name, overwrite=False):
    """
    Write a prody protein to a pdb file.

    Args:
        protein: protein object from prody
        pdb_name: base name for the pdb file
        overwrite: whether to overwrite an already existing file

    Returns: file name

    """

    output_protein_name = f"{pdb_name}.pdb"

    # check if file already exists
    if not overwrite and os.path.isfile(os.path.join(os.getcwd(), output_protein_name)):
        print(f"The protein file for the PDB entry {pdb_name} already exists. "
              f"Set overwrite=True if you want to overwrite it.")
    else:
        writePDB(output_protein_name, protein)
        print(f"Wrote the protein file for the PDB entry {output_protein_name}.")

    return output_protein_name


def write_sdf(new_mol, pdb_name, res_name, overwrite=False):
    """
    Write an RDKit molecule to an SD file.

    Args:
        new_mol: the molecule to write to a file
        pdb_name: the PDB entry from which it was extracted
        res_name: its residue identifier in the PDB entry
        overwrite: whether to overwrite an already existing file

    Returns: file name

    """

    outfile_ligand_name = f"{pdb_name}_{res_name}_ligand.sdf"

    # check if file already exists
    if not overwrite and os.path.isfile(os.path.join(os.getcwd(), outfile_ligand_name)):
        print(f"The ligand file for the ligand {res_name} in PDB entry {pdb_name} already exists. "
              f"Set overwrite=True if you want to overwrite it.")
    else:
        writer = Chem.SDWriter(outfile_ligand_name)
        writer.write(new_mol)
        print(f"wrote the ligand file for the ligand {res_name} in PDB entry {pdb_name}.")

    return outfile_ligand_name
